= Logback, customização de campos e formatação em JSON

- Uso da dependência: https://github.com/logfellow/logstash-logback-encoder
- Criação de um JsonProvider customizado
- Uso de variáveis de ambiente do Spring
- Customização do layout de acordo com o profile do Spring
- Habilitar pretty print com profile do Spring
- Ofuscação de dados sensíveis com configuração via Environment
- Implementação simples de LogAOP em dependência apartada e opcional

== Uso

=== Logar no formato padrão

Para isso, basta informar o profile: `default-format`

Por exemplo, com variável de VM: `-Dspring.profiles.active=default-format`

Para informar mais de um profile, basta passar os outros profiles separados por vírgulas: `-Dspring.profiles.active=default-format,dev`

=== Habilitar Pretty Print Json

Para isso, basta informar o profile: `pretty-print-json`

Por exemplo, com variável de VM: `-Dspring.profiles.active=pretty-print-json`

Para informar mais de um profile, basta passar os outros profiles separados por vírgulas: `-Dspring.profiles.active=pretty-print-json,dev`

=== Ofuscação de dados sensíveis

Para isso, basta informar as propriedades no `application.properties`, onde:

- `config.mask.cpf`: Os caminhos do log onde será aplicada a máscara de CPF, separados por vírgulas. Permite também valores absolutos e uso de wild card. Exemplo: `cliente/cpf,cpf,*/cpf`
- `config.mask.cnpj`: Os caminhos do log onde será aplicada a máscara de CPF, separados por vírgulas. Permite também valores absolutos e uso de wild card. Exemplo: `cliente/cnpj,cnpj,*/cnpj`
- `config.mask.hidden`: Os caminhos do log onde será aplicada a ofuscação do valor, separados por vírgulas. Permite também valores absolutos e uso de wild card. Exemplo: `cliente/endereco,endereco,*/endereco`

==== Criando o próprio mecanismo de `masking`

É possível criar um mecanismo do lado da aplicação. O jeito mais simples é criar uma classe que estenda da classe `BaseMask`. Exemplo:

[source,java]
----
public class MyCustomMask extends BaseMask {

    public MyCustomMask(Environment environment) {
        super(environment);
    }

    @Override
    public String getType() {
        return "custom";
    }

    @Override
    public Object mask(Object value) {
        return "XoX";
    }
}
----

Com essa implementação será necessário adicionar na aplicação uma chave `config.mask.custom` onde `custom` corresponde ao `type` da classe de implementação.

Será necessário também criar um bean dessa implementação:

[source,java]
----
@Bean
public MyCustomMask myCustomMask(Environment environment) {
    return new MyCustomMask(environment);
}
----

Com isso, todos os `paths` configurados na chave `config.mask.custom` serão substituídos por `XoX`. O valor recebido por parâmetro é o valor original, o valor retornado é o valor desejado após a transformação.

=== Log AOP

É disponibilizada uma anotação que pode ser inserida a nível de método e classe: `@LogAop`.
No momento, a anotação apenas gera o log com as informações padrões, capturando a classe de origem para inserção do log e utilizando `Markers` para acrescentar um atributo `method` com o nome do método de origem.